while( true )
do
turtle.select(1)
turtle.placeDown()
turtle.turnLeft()
turtle.forward()
turtle.select(2)
turtle.placeDown()
turtle.turnRight()
turtle.forward()
turtle.select(3)
turtle.placeDown()
turtle.turnRight()
turtle.forward()
turtle.turnLeft()
end
